language: node_js
node_js:
  - "node"
before_install:
  - echo 'befpre install' 
install:
  - echo 'install' 
before_script:
  - echo 'before_script' 
script:
  - echo 'script' 
after_success:
  - echo 'after_success' 
after_failure:
  - echo 'after_failure' 
before_depl y:
  - echo 'before_deploy' 
deplpy:
  - echo 'deploy' 
after_depl y:
  - echo 'after_deplpy' 

